[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
ndarray = "0.15.6"
#numpy = "0.20.0"
regex = "1.10.2"
lazy_static = "1.4.0"
itertools = "0.12.0"
kdam = "0.5.1"
